language: go

dist: bionic

go:
    - 1.14.x

go_import_path: github.com/yktoo/ymuse

addons:
    apt:
        packages:
            - libgtk-3-dev

install:
    - go mod download

script:
    # Verify no formatting issues
    - test `gofmt -l . | wc -l` = 0

    # Run tests
    - go test -v ./...

    # Verify goreleaser config
    - curl -sfL https://git.io/goreleaser | bash -s -- check

after_success:
    # Run goreleaser without deploying
    - curl -sfL https://git.io/goreleaser | bash -s -- --rm-dist --skip-publish --snapshot
