language: go
go:
  - 1.14.x

go_import_path: github.com/yktoo/ymuse

before_install:
    - sudo apt-get -y install libgtk-3-dev

script:
    - go install -v ./...
    # Verify no formatting issues
    - test `gofmt -l . | wc -l` = 0
    # Run tests
    - go test -v ./...
