language: go

dist: bionic

go:
    - 1.14.x

go_import_path: github.com/yktoo/ymuse

addons:
    apt:
        packages:
            - libgtk-3-dev
            - xvfb
    snaps:
        - name: snapcraft
          confinement: classic

before_install:
    # Run in Xvfb
    - "export DISPLAY=:99.0"
    - sudo /usr/bin/Xvfb $DISPLAY &>/dev/null &

install:
    - go generate
    - go mod download

script:
    # Verify no formatting issues
    - test `gofmt -l . | wc -l` = 0

    # Run tests
    - go test -v ./...

    # Verify goreleaser config
    - curl -sfL https://git.io/goreleaser | bash -s -- check

deploy:
    - provider: script
      skip_cleanup: true
      script: curl -sfL https://git.io/goreleaser | bash
      on:
          branch: master
          tags: true
          condition: $TRAVIS_OS_NAME = linux

    # Make a snap AFTER goreleaser built everything
    - provider: script
      skip_cleanup: true
      script: snapcraft snap --destructive-mode
      on:
          all_branches: true

    # Publish dev branch builds to the edge channel
    - provider: snap
      snap: ymuse_*.snap
      channel: edge
      skip_cleanup: true
      on:
          branch: dev

    # Publish master branch builds to the stable channel
    - provider: snap
      snap: ymuse_*.snap
      channel: stable
      skip_cleanup: true
      on:
          branch: master
          tags: true
