language: go

dist: bionic

go:
    - 1.14.x

go_import_path: github.com/yktoo/ymuse

addons:
    apt:
        packages:
            - libgtk-3-dev

install:
    - go get github.com/magefile/mage
    - mage build

script:
    # Verify no formatting issues
    - test `gofmt -l . | wc -l` = 0

    # Run tests
    - go test -v ./...

    # Verify goreleaser config
    - curl -sfL https://git.io/goreleaser | bash -s -- check
